name: bio
description: A dart package to aid in the development of solutions to problems related to biology.
version: 1.0.0
homepage: https://github.com/oberdancunha/dart-bio-package/tree/version-1.0.0

environment:
  sdk: ">=2.12.3 <3.0.0"
  flutter: ">=2.0.6"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.3
  kt_dart: ^0.9.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  dart_code_metrics: ^3.2.3
  freezed: ^0.14.2
  lint: ^1.5.3
  mocktail: ^0.1.4

flutter: null





























