name: dart_bio_package
description: A dart package to aid in the development of solutions to problems related to biology.
version: 2.1.0
homepage: https://github.com/oberdancunha/dart-bio-package/tree/2.1.0
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=3.3.6"

dependencies:
  flutter:
    sdk: flutter
  dart_bio_seqio:
    git: 
      url: https://github.com/oberdancunha/dart-bio-package.git
      ref: 2.1.0
      path: dart_bio_seqio

dev_dependencies:
  dart_code_metrics: ^5.6.0
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
  melos: ^3.1.0

flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
