name: dart_bio_core
description: A dart project to implement core project.
version: 2.1.0
homepage: https://github.com/oberdancunha/dart-bio-package/tree/2.1.0
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=3.3.6"

dependencies:
  flutter:
    sdk: flutter
  dart_bio_dependency_module:
    git: 
      url: https://github.com/oberdancunha/dart-bio-package.git
      ref: 2.1.0
      path: dart_bio_dependency_module

dev_dependencies:
  dart_code_metrics: ^5.6.0
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
