name: dart_bio_dependency_module
description: A dart project to manage libraries to be used throughout the project..
version: 2.0.0
homepage: https://github.com/oberdancunha/dart-bio-package/tree/2.0.0

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=3.3.6"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  fpdart: ^0.5.0
  kt_dart: ^1.0.0
  sealed_unions: ^3.0.3+1

dev_dependencies:
  dart_code_metrics: ^4.19.2
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter: null





























